# Generated by Django 5.0.1 on 2024-08-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbre',
            name='capacite_Salle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arbre',
            name='nombre_participants',
            field=models.IntegerField(default=0),
        ),
    ]
