# Generated by Django 5.0.1 on 2024-08-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devA', '0002_arbre_capacite_salle_arbre_nombre_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbre',
            name='statut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arbre',
            name='valided',
            field=models.BooleanField(default=False),
        ),
    ]
