# Generated by Django 5.0.1 on 2024-08-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devA', '0003_arbre_statut_arbre_valided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbre',
            name='statut',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='arbre',
            name='valided',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
